using System.ServiceModel.Description;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomizationWebApi.Client
{
    internal static class HelperClass
    {

        public static void ConfigureCredentials(ServiceEndpoint serviceEndpoint, ClientCredentials clientCredentials)
        {
            byte[] credentialBuffer = new System.Text.UTF8Encoding().GetBytes("sb-f4714fc3-b963-429e-ac49-540a3d541483!b36509|it-rt-citscpicfdev!b16077" + ":" + "3c15038d-7367-4547-a278-fd4a8103e2bd$K9O5xJnpVoBv-bKLQT0Rcl46Mfi6DOutqJQuUxilnRg=");
            var headers = new Dictionary<string, string>
            {
                {"Authorization", "Basic " + Convert.ToBase64String(credentialBuffer)}
            };

            var behavior = new AddHttpHeaderMessageEndpointBehavior(headers);
            serviceEndpoint.EndpointBehaviors.Add(behavior);

            clientCredentials.UserName.UserName = "sb-f4714fc3-b963-429e-ac49-540a3d541483!b36509|it-rt-citscpicfdev!b16077";
            clientCredentials.UserName.Password = "3c15038d-7367-4547-a278-fd4a8103e2bd$K9O5xJnpVoBv-bKLQT0Rcl46Mfi6DOutqJQuUxilnRg=";
        }
    }
}