//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace CustomizationWebApi.Client.Cost
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions", ConfigurationName = "FTI.zLIMS_ACT_COSTS_GET")]
    public interface zLIMS_ACT_COSTS_GET
    {

        [System.ServiceModel.OperationContractAttribute(Action = "urn:sap-com:document:sap:rfc:functions:zLIMS_ACT_COSTS_GET:Z_QM_ACT_COSTSRequest", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<Z_QM_ACT_COSTSResponse1> Z_QM_ACT_COSTSAsync(Z_QM_ACT_COSTSRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [DataContract(Namespace = "urn")]
    [XmlType(Namespace = "urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_QM_ACT_COSTS
    {

        private string iV_PLANTField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string IV_PLANT
        {
            get
            {
                return this.iV_PLANTField;
            }
            set
            {
                this.iV_PLANTField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2
    {

        private string tYPEField;

        private string idField;

        private string nUMBERField;

        private string mESSAGEField;

        private string lOG_NOField;

        private string lOG_MSG_NOField;

        private string mESSAGE_V1Field;

        private string mESSAGE_V2Field;

        private string mESSAGE_V3Field;

        private string mESSAGE_V4Field;

        private string pARAMETERField;

        private int rOWField;

        private string fIELDField;

        private string sYSTEMField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string LOG_NO
        {
            get
            {
                return this.lOG_NOField;
            }
            set
            {
                this.lOG_NOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string LOG_MSG_NO
        {
            get
            {
                return this.lOG_MSG_NOField;
            }
            set
            {
                this.lOG_MSG_NOField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string MESSAGE_V1
        {
            get
            {
                return this.mESSAGE_V1Field;
            }
            set
            {
                this.mESSAGE_V1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string MESSAGE_V2
        {
            get
            {
                return this.mESSAGE_V2Field;
            }
            set
            {
                this.mESSAGE_V2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string MESSAGE_V3
        {
            get
            {
                return this.mESSAGE_V3Field;
            }
            set
            {
                this.mESSAGE_V3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string MESSAGE_V4
        {
            get
            {
                return this.mESSAGE_V4Field;
            }
            set
            {
                this.mESSAGE_V4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string PARAMETER
        {
            get
            {
                return this.pARAMETERField;
            }
            set
            {
                this.pARAMETERField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public int ROW
        {
            get
            {
                return this.rOWField;
            }
            set
            {
                this.rOWField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string FIELD
        {
            get
            {
                return this.fIELDField;
            }
            set
            {
                this.fIELDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string SYSTEM
        {
            get
            {
                return this.sYSTEMField;
            }
            set
            {
                this.sYSTEMField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions")]
    public partial class ZQM_S_ACT_COSTS
    {

        private string wERKSField;

        private string aRBPLField;

        private string kOKRSField;

        private string kOSTLField;

        private string lSTARField;

        private string gJAHRField;

        private string uNITField;

        private decimal tKG001Field;

        private decimal tKG002Field;

        private decimal tKG003Field;

        private decimal tKG004Field;

        private decimal tKG005Field;

        private decimal tKG006Field;

        private decimal tKG007Field;

        private decimal tKG008Field;

        private decimal tKG009Field;

        private decimal tKG010Field;

        private decimal tKG011Field;

        private decimal tKG012Field;

        private decimal tKG013Field;

        private decimal tKG014Field;

        private decimal tKG015Field;

        private decimal tKG016Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string WERKS
        {
            get
            {
                return this.wERKSField;
            }
            set
            {
                this.wERKSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ARBPL
        {
            get
            {
                return this.aRBPLField;
            }
            set
            {
                this.aRBPLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string KOKRS
        {
            get
            {
                return this.kOKRSField;
            }
            set
            {
                this.kOKRSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string KOSTL
        {
            get
            {
                return this.kOSTLField;
            }
            set
            {
                this.kOSTLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string LSTAR
        {
            get
            {
                return this.lSTARField;
            }
            set
            {
                this.lSTARField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string GJAHR
        {
            get
            {
                return this.gJAHRField;
            }
            set
            {
                this.gJAHRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string UNIT
        {
            get
            {
                return this.uNITField;
            }
            set
            {
                this.uNITField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public decimal TKG001
        {
            get
            {
                return this.tKG001Field;
            }
            set
            {
                this.tKG001Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public decimal TKG002
        {
            get
            {
                return this.tKG002Field;
            }
            set
            {
                this.tKG002Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public decimal TKG003
        {
            get
            {
                return this.tKG003Field;
            }
            set
            {
                this.tKG003Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public decimal TKG004
        {
            get
            {
                return this.tKG004Field;
            }
            set
            {
                this.tKG004Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public decimal TKG005
        {
            get
            {
                return this.tKG005Field;
            }
            set
            {
                this.tKG005Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public decimal TKG006
        {
            get
            {
                return this.tKG006Field;
            }
            set
            {
                this.tKG006Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public decimal TKG007
        {
            get
            {
                return this.tKG007Field;
            }
            set
            {
                this.tKG007Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public decimal TKG008
        {
            get
            {
                return this.tKG008Field;
            }
            set
            {
                this.tKG008Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public decimal TKG009
        {
            get
            {
                return this.tKG009Field;
            }
            set
            {
                this.tKG009Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public decimal TKG010
        {
            get
            {
                return this.tKG010Field;
            }
            set
            {
                this.tKG010Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
        public decimal TKG011
        {
            get
            {
                return this.tKG011Field;
            }
            set
            {
                this.tKG011Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public decimal TKG012
        {
            get
            {
                return this.tKG012Field;
            }
            set
            {
                this.tKG012Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 19)]
        public decimal TKG013
        {
            get
            {
                return this.tKG013Field;
            }
            set
            {
                this.tKG013Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 20)]
        public decimal TKG014
        {
            get
            {
                return this.tKG014Field;
            }
            set
            {
                this.tKG014Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 21)]
        public decimal TKG015
        {
            get
            {
                return this.tKG015Field;
            }
            set
            {
                this.tKG015Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 22)]
        public decimal TKG016
        {
            get
            {
                return this.tKG016Field;
            }
            set
            {
                this.tKG016Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_QM_ACT_COSTSResponse
    {

        private ZQM_S_ACT_COSTS[] eT_COSTSField;

        private BAPIRET2[] eT_RETURNField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ZQM_S_ACT_COSTS[] ET_COSTS
        {
            get
            {
                return this.eT_COSTSField;
            }
            set
            {
                this.eT_COSTSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public BAPIRET2[] ET_RETURN
        {
            get
            {
                return this.eT_RETURNField;
            }
            set
            {
                this.eT_RETURNField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class Z_QM_ACT_COSTSRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions", Order = 0)]
        public Z_QM_ACT_COSTS Z_QM_ACT_COSTS;

        public Z_QM_ACT_COSTSRequest()
        {
        }

        public Z_QM_ACT_COSTSRequest(Z_QM_ACT_COSTS Z_QM_ACT_COSTS)
        {
            this.Z_QM_ACT_COSTS = Z_QM_ACT_COSTS;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class Z_QM_ACT_COSTSResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:sap-com:document:sap:rfc:functions", Order = 0)]
        public Z_QM_ACT_COSTSResponse Z_QM_ACT_COSTSResponse;

        public Z_QM_ACT_COSTSResponse1()
        {
        }

        public Z_QM_ACT_COSTSResponse1(Z_QM_ACT_COSTSResponse Z_QM_ACT_COSTSResponse)
        {
            this.Z_QM_ACT_COSTSResponse = Z_QM_ACT_COSTSResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface zLIMS_ACT_COSTS_GETChannel : zLIMS_ACT_COSTS_GET, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class zLIMS_ACT_COSTS_GETClient : System.ServiceModel.ClientBase<zLIMS_ACT_COSTS_GET>, zLIMS_ACT_COSTS_GET
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials)
        {
            HelperClass.ConfigureCredentials(serviceEndpoint, clientCredentials);
        }

        public zLIMS_ACT_COSTS_GETClient() :
                base(zLIMS_ACT_COSTS_GETClient.GetDefaultBinding(), zLIMS_ACT_COSTS_GETClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ZLIMS_ACT_COSTS_GET_WS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public zLIMS_ACT_COSTS_GETClient(EndpointConfiguration endpointConfiguration) :
                base(zLIMS_ACT_COSTS_GETClient.GetBindingForEndpoint(endpointConfiguration), zLIMS_ACT_COSTS_GETClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public zLIMS_ACT_COSTS_GETClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(zLIMS_ACT_COSTS_GETClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public zLIMS_ACT_COSTS_GETClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(zLIMS_ACT_COSTS_GETClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public zLIMS_ACT_COSTS_GETClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Z_QM_ACT_COSTSResponse1> zLIMS_ACT_COSTS_GET.Z_QM_ACT_COSTSAsync(Z_QM_ACT_COSTSRequest request)
        {
            return base.Channel.Z_QM_ACT_COSTSAsync(request);
        }

        public System.Threading.Tasks.Task<Z_QM_ACT_COSTSResponse1> Z_QM_ACT_COSTSAsync(Z_QM_ACT_COSTS Z_QM_ACT_COSTS)
        {
            Z_QM_ACT_COSTSRequest inValue = new Z_QM_ACT_COSTSRequest();
            inValue.Z_QM_ACT_COSTS = Z_QM_ACT_COSTS;
            return ((zLIMS_ACT_COSTS_GET)(this)).Z_QM_ACT_COSTSAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZLIMS_ACT_COSTS_GET_WS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZLIMS_ACT_COSTS_GET_WS))
            {
                return new System.ServiceModel.EndpointAddress("https://citscpicfdev.it-cpi001-rt.cfapps.eu10.hana.ondemand.com/cxf/THERMOFISCHER" +
                        "/ERP/Z_QM_ACT_COSTS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return zLIMS_ACT_COSTS_GETClient.GetBindingForEndpoint(EndpointConfiguration.ZLIMS_ACT_COSTS_GET_WS);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return zLIMS_ACT_COSTS_GETClient.GetEndpointAddress(EndpointConfiguration.ZLIMS_ACT_COSTS_GET_WS);
        }

        public enum EndpointConfiguration
        {

            ZLIMS_ACT_COSTS_GET_WS,
        }
    }
}
